import React from 'react';
import Layout from '../components/Layout/Layout';
import Article from '../components/Article/Article';
import Form1 from '../components/Forms/Form1/Form1'; // Adjusted the path to match the correct location

const HelpDeskPage: React.FC = () => {
  return (
    <Layout>
      <section id="offices_section">
        <h2 className="fRow fCenter colHeading">Market segments 2026 Q3</h2>
        <div className="fRow fCenter aAlignItemsCenter offices">
          <div className="fCol leftCol">
            <h3>Asia</h3>
            <ul>
              <li>Singapore</li>
              <li>Kathmandu</li>
            </ul>
          </div>
          <div className="fCol midCol">
            <h3>North America</h3>
            <ul>
              <li>Toronto, Canada</li>
              <li>Denver, USA</li>
            </ul>
          </div>
          <div className="fCol rightCol">
            <h3>Australia</h3>
            <ul>
              <li>Adelaide</li>
              <li>Sydney</li>
            </ul>
          </div>
        </div>
      </section>

      <section>
        <Article
          title="Let’s transform work with Necessity driven design..."
          content="Welcome to my personal website where every visitor smiles with a gaze at an interesting offer to collaborate and discover how profitable necessity driven design, automation and marketing is going to be..."
          imageSrc="/png/no-image.png"
          linkText="Continue Reading"
          linkHref="/display.html?id=2"
        />
      </section>

      <section id="about">
        <Article
          title="Automate Digital Business, TODAY!"
          content="Transform your marketing strategy with cutting-edge automation service at affordable rates! Harness the power of Google, Facebook and Bing Analytics to gain valuable insights and inform the content generated by ChatGPT..."
          imageSrc="/png/no-image.png"
          linkText="Continue Reading"
          linkHref="/display.html?id=2"
        />
      </section>

      <section id="formSection" className="aa">
        <Form1 />
        <article className="block aa information">
          <br />
          <div>
            <h2>Let's grow together</h2>
            <p>
              Please select a topic below related to your inquiry.
              <br />
              If you don't find what you need, fill out the form:
            </p>
          </div>
          <div>
            <h3><a href="#">Book a demo</a></h3>
            <p>Live in-person demo to clear confusion</p>
          </div>
          <div>
            <h3><a href="#">Order here</a></h3>
            <p>Order available services if you liked the demo</p>
          </div>
          <div>
            <h3><a href="#">Let's Collaborate</a></h3>
            <p>Please share requirements for collaboration</p>
          </div>
        </article>
      </section>
    </Layout>
  );
};

export default HelpDeskPage;
